/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u11051489121
 */
public class JDlgDam_Usuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgDam_Usuarios
     */
    public JDlgDam_Usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuários.");
        setLocationRelativeTo(null);
        
        jTxtDam_Codigo.setEnabled(false);
        jTxtDam_Apelido.setEnabled(false);
        jTxtDam_Nome.setEnabled(false);
        jFmtDam_Cpf.setEnabled(false);
        jPwfDam_Senha.setEnabled(false);
        jFmtDam_Data.setEnabled(false);
        jChbDam_Ativo.setEnabled(false);
        jBtnDam_Cancelar.setEnabled(false);
        jBtnDam_Confirmar.setEnabled(false);

    }
    
    public void habilitar(){
        jTxtDam_Codigo.setEnabled(true);
        jTxtDam_Apelido.setEnabled(true);
        jTxtDam_Nome.setEnabled(true);
        jFmtDam_Cpf.setEnabled(true);
        jPwfDam_Senha.setEnabled(true);
        jFmtDam_Data.setEnabled(true);
        jChbDam_Ativo.setEnabled(true);
        jBtnDam_Cancelar.setEnabled(true);
        jBtnDam_Confirmar.setEnabled(true);
        jBtnDam_Incluir.setEnabled(false);
        jBtnDam_Alterar.setEnabled(false);
        jBtnDam_Excluir.setEnabled(false);
        jBtnDam_Pesquisar.setEnabled(false);
    }
    
    public void desabilitar(){
        jTxtDam_Codigo.setEnabled(false);
        jTxtDam_Apelido.setEnabled(false);
        jTxtDam_Nome.setEnabled(false);
        jFmtDam_Cpf.setEnabled(false);
        jPwfDam_Senha.setEnabled(false);
        jFmtDam_Data.setEnabled(false);
        jChbDam_Ativo.setEnabled(false);
        jBtnDam_Cancelar.setEnabled(false);
        jBtnDam_Confirmar.setEnabled(false);
        jBtnDam_Incluir.setEnabled(true);
        jBtnDam_Alterar.setEnabled(true);
        jBtnDam_Excluir.setEnabled(true);
        jBtnDam_Pesquisar.setEnabled(true);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Dam_Codigo = new javax.swing.JLabel();
        jTxtDam_Codigo = new javax.swing.JTextField();
        jLabel1Dam_Nome = new javax.swing.JLabel();
        jTxtDam_Nome = new javax.swing.JTextField();
        jLabel3Dam_Apelido = new javax.swing.JLabel();
        jTxtDam_Apelido = new javax.swing.JTextField();
        jLabel3Dam_Cpf = new javax.swing.JLabel();
        jFmtDam_Cpf = new javax.swing.JFormattedTextField();
        jLabel3Dam_DataNascimento = new javax.swing.JLabel();
        jFmtDam_Data = new javax.swing.JFormattedTextField();
        jLabel3Dam_Senha = new javax.swing.JLabel();
        jPwfDam_Senha = new javax.swing.JPasswordField();
        jChbDam_Ativo = new javax.swing.JCheckBox();
        jBtnDam_Incluir = new javax.swing.JButton();
        jBtnDam_Alterar = new javax.swing.JButton();
        jBtnDam_Excluir = new javax.swing.JButton();
        jBtnDam_Confirmar = new javax.swing.JButton();
        jBtnDam_Pesquisar = new javax.swing.JButton();
        jBtnDam_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Dam_Codigo.setText("Código");

        jTxtDam_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDam_CodigoActionPerformed(evt);
            }
        });

        jLabel1Dam_Nome.setText("Nome");

        jLabel3Dam_Apelido.setText("Apelido");

        jLabel3Dam_Cpf.setText("CPF");

        jLabel3Dam_DataNascimento.setText("Data de Nascimento");

        jLabel3Dam_Senha.setText("Senha");

        jPwfDam_Senha.setText("jPasswordField1");

        jChbDam_Ativo.setText("Ativo");

        jBtnDam_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnDam_Incluir.setText("Incluir");
        jBtnDam_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_IncluirActionPerformed(evt);
            }
        });

        jBtnDam_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnDam_Alterar.setText("Alterar");
        jBtnDam_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_AlterarActionPerformed(evt);
            }
        });

        jBtnDam_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnDam_Excluir.setText("Excluir");
        jBtnDam_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_ExcluirActionPerformed(evt);
            }
        });

        jBtnDam_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnDam_Confirmar.setText("Confirmar");
        jBtnDam_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_ConfirmarActionPerformed(evt);
            }
        });

        jBtnDam_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnDam_Pesquisar.setText("Pesquisar");
        jBtnDam_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_PesquisarActionPerformed(evt);
            }
        });

        jBtnDam_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnDam_Cancelar.setText("Cancelar");
        jBtnDam_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1Dam_Codigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDam_Codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDam_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1Dam_Nome)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jFmtDam_Data, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                        .addComponent(jLabel3Dam_Apelido, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtDam_Apelido, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel3Dam_DataNascimento))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtDam_Cpf)
                                    .addComponent(jLabel3Dam_Senha)
                                    .addComponent(jLabel3Dam_Cpf)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPwfDam_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jChbDam_Ativo)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnDam_Incluir)
                        .addGap(26, 26, 26)
                        .addComponent(jBtnDam_Alterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnDam_Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDam_Confirmar)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jBtnDam_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnDam_Pesquisar)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1Dam_Codigo)
                    .addComponent(jLabel1Dam_Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDam_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Dam_Apelido)
                    .addComponent(jLabel3Dam_Cpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDam_Apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtDam_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3Dam_DataNascimento)
                    .addComponent(jLabel3Dam_Senha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtDam_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPwfDam_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbDam_Ativo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDam_Incluir)
                    .addComponent(jBtnDam_Alterar)
                    .addComponent(jBtnDam_Excluir)
                    .addComponent(jBtnDam_Confirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDam_Pesquisar)
                    .addComponent(jBtnDam_Cancelar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDam_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDam_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDam_CodigoActionPerformed

    private void jBtnDam_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnDam_IncluirActionPerformed

    private void jBtnDam_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_CancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnDam_CancelarActionPerformed

    private void jBtnDam_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnDam_AlterarActionPerformed

    private void jBtnDam_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_ConfirmarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnDam_ConfirmarActionPerformed

    private void jBtnDam_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirma Exclusão?");
    }//GEN-LAST:event_jBtnDam_ExcluirActionPerformed

    private void jBtnDam_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_PesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showInputDialog(null, "Entre com a chave primária:");
    }//GEN-LAST:event_jBtnDam_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgDam_Usuarios dialog = new JDlgDam_Usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDam_Alterar;
    private javax.swing.JButton jBtnDam_Cancelar;
    private javax.swing.JButton jBtnDam_Confirmar;
    private javax.swing.JButton jBtnDam_Excluir;
    private javax.swing.JButton jBtnDam_Incluir;
    private javax.swing.JButton jBtnDam_Pesquisar;
    private javax.swing.JCheckBox jChbDam_Ativo;
    private javax.swing.JFormattedTextField jFmtDam_Cpf;
    private javax.swing.JFormattedTextField jFmtDam_Data;
    private javax.swing.JLabel jLabel1Dam_Codigo;
    private javax.swing.JLabel jLabel1Dam_Nome;
    private javax.swing.JLabel jLabel3Dam_Apelido;
    private javax.swing.JLabel jLabel3Dam_Cpf;
    private javax.swing.JLabel jLabel3Dam_DataNascimento;
    private javax.swing.JLabel jLabel3Dam_Senha;
    private javax.swing.JPasswordField jPwfDam_Senha;
    private javax.swing.JTextField jTxtDam_Apelido;
    private javax.swing.JTextField jTxtDam_Codigo;
    private javax.swing.JTextField jTxtDam_Nome;
    // End of variables declaration//GEN-END:variables
}
