/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u11051489121
 */
public class JDlgDam_Fornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgDam_Fornecedor
     */
    public JDlgDam_Fornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Fornecedor.");
        setLocationRelativeTo(null);
        
        jTxtDam_Codigo.setEnabled(false);
        jTxtDam_NomeFantasia.setEnabled(false);
        jTxtDam_RazãoSocial.setEnabled(false);
        jTxtDam_CNPJ.setEnabled(false);
        jTxtDam_ContatoResponsavel.setEnabled(false);
        jTxtDam_Email.setEnabled(false);
        jTxtDam_Endereço.setEnabled(false);
        jTxtDam_Numero.setEnabled(false);
        jTxtDam_Telefone.setEnabled(false);
        jTxtDam_InscriçãoEstadual.setEnabled(false);
        jTxtDam_Cep.setEnabled(false);
        jTxtDam_Cidade.setEnabled(false);
        jTxtDam_Estado.setEnabled(false);
        jTxtDam_Bairro.setEnabled(false);
        jChbDam_Ativo.setEnabled(false);
        jBtnDam_Cancelar.setEnabled(false);
        jBtnDam_Confirmar.setEnabled(false);

    }
    
    public void habilitar(){
        jTxtDam_Codigo.setEnabled(true);
        jTxtDam_NomeFantasia.setEnabled(true);
        jTxtDam_RazãoSocial.setEnabled(true);
        jTxtDam_CNPJ.setEnabled(true);
        jTxtDam_ContatoResponsavel.setEnabled(true);
        jTxtDam_Email.setEnabled(true);
        jTxtDam_Endereço.setEnabled(true);
        jTxtDam_Numero.setEnabled(true);
        jTxtDam_Telefone.setEnabled(true);
        jTxtDam_InscriçãoEstadual.setEnabled(true);
        jTxtDam_Cep.setEnabled(true);
        jTxtDam_Cidade.setEnabled(true);
        jTxtDam_Estado.setEnabled(true);
        jTxtDam_Bairro.setEnabled(true);
        jChbDam_Ativo.setEnabled(true);
        jBtnDam_Cancelar.setEnabled(true);
        jBtnDam_Confirmar.setEnabled(true);
        jBtnDam_Incluir.setEnabled(false);
        jBtnDam_Alterar.setEnabled(false);
        jBtnDam_Excluir.setEnabled(false);
        jBtnDam_Pesquisar.setEnabled(false);
    }
    
    public void desabilitar(){
        jTxtDam_Codigo.setEnabled(false);
        jTxtDam_NomeFantasia.setEnabled(false);
        jTxtDam_RazãoSocial.setEnabled(false);
        jTxtDam_CNPJ.setEnabled(false);
        jTxtDam_ContatoResponsavel.setEnabled(false);
        jTxtDam_Email.setEnabled(false);
        jTxtDam_Endereço.setEnabled(false);
        jTxtDam_Numero.setEnabled(false);
        jTxtDam_Telefone.setEnabled(false);
        jTxtDam_InscriçãoEstadual.setEnabled(false);
        jTxtDam_Cep.setEnabled(false);
        jTxtDam_Cidade.setEnabled(false);
        jTxtDam_Estado.setEnabled(false);
        jTxtDam_Bairro.setEnabled(false);
        jChbDam_Ativo.setEnabled(false);
        jBtnDam_Cancelar.setEnabled(false);
        jBtnDam_Confirmar.setEnabled(false);
        jBtnDam_Incluir.setEnabled(true);
        jBtnDam_Alterar.setEnabled(true);
        jBtnDam_Excluir.setEnabled(true);
        jBtnDam_Pesquisar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Dam_Codigo = new javax.swing.JLabel();
        jTxtDam_Codigo = new javax.swing.JTextField();
        jLabel2Dam_NomeFantasia = new javax.swing.JLabel();
        jTxtDam_NomeFantasia = new javax.swing.JTextField();
        jLabel3Dam_RazãoSocial = new javax.swing.JLabel();
        jTxtDam_RazãoSocial = new javax.swing.JTextField();
        jLabel4Dam_CNPJ = new javax.swing.JLabel();
        jTxtDam_CNPJ = new javax.swing.JTextField();
        jLabel5Dam_Email = new javax.swing.JLabel();
        jTxtDam_Email = new javax.swing.JTextField();
        jLabel6Dam_Telefone = new javax.swing.JLabel();
        jTxtDam_Telefone = new javax.swing.JTextField();
        jLabel7Dam_Cep = new javax.swing.JLabel();
        jTxtDam_Cep = new javax.swing.JTextField();
        jLabel8Dam_Endereço = new javax.swing.JLabel();
        jTxtDam_Endereço = new javax.swing.JTextField();
        jLabel9Dam_Numero = new javax.swing.JLabel();
        jTxtDam_Numero = new javax.swing.JTextField();
        jLabel10Dam_Bairro = new javax.swing.JLabel();
        jTxtDam_Bairro = new javax.swing.JTextField();
        jLabel11Dam_Estado = new javax.swing.JLabel();
        jTxtDam_Estado = new javax.swing.JTextField();
        jLabel12Dam_Cidade = new javax.swing.JLabel();
        jTxtDam_Cidade = new javax.swing.JTextField();
        jLabel13Dam_InscriçãoEstadual = new javax.swing.JLabel();
        jTxtDam_InscriçãoEstadual = new javax.swing.JTextField();
        jLabel14Dam_ContatoResponsavel = new javax.swing.JLabel();
        jTxtDam_ContatoResponsavel = new javax.swing.JTextField();
        jChbDam_Ativo = new javax.swing.JCheckBox();
        jBtnDam_Incluir = new javax.swing.JButton();
        jBtnDam_Alterar = new javax.swing.JButton();
        jBtnDam_Excluir = new javax.swing.JButton();
        jBtnDam_Confirmar = new javax.swing.JButton();
        jBtnDam_Cancelar = new javax.swing.JButton();
        jBtnDam_Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1Dam_Codigo.setText("Código");

        jLabel2Dam_NomeFantasia.setText("Nome fantasia");

        jLabel3Dam_RazãoSocial.setText("Razão Social");

        jLabel4Dam_CNPJ.setText("CNPJ");

        jLabel5Dam_Email.setText("E-mail");

        jLabel6Dam_Telefone.setText("Telefone");

        jLabel7Dam_Cep.setText("CEP");

        jLabel8Dam_Endereço.setText("Endereço");

        jLabel9Dam_Numero.setText("Numero");

        jLabel10Dam_Bairro.setText("Bairro");

        jLabel11Dam_Estado.setText("Estado");

        jLabel12Dam_Cidade.setText("Cidade");

        jLabel13Dam_InscriçãoEstadual.setText("Inscrição Estadual");

        jLabel14Dam_ContatoResponsavel.setText("Contato do Responsavel");

        jTxtDam_ContatoResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDam_ContatoResponsavelActionPerformed(evt);
            }
        });

        jChbDam_Ativo.setText("Ativo");

        jBtnDam_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnDam_Incluir.setText("Incluir");
        jBtnDam_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_IncluirActionPerformed(evt);
            }
        });

        jBtnDam_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnDam_Alterar.setText("Alterar");
        jBtnDam_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_AlterarActionPerformed(evt);
            }
        });

        jBtnDam_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnDam_Excluir.setText("Excluir");
        jBtnDam_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_ExcluirActionPerformed(evt);
            }
        });

        jBtnDam_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar.png"))); // NOI18N
        jBtnDam_Confirmar.setText("Confirmar");
        jBtnDam_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_ConfirmarActionPerformed(evt);
            }
        });

        jBtnDam_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnDam_Cancelar.setText("Cancelar");
        jBtnDam_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_CancelarActionPerformed(evt);
            }
        });

        jBtnDam_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnDam_Pesquisar.setText("Pesquisar");
        jBtnDam_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDam_PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDam_InscriçãoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13Dam_InscriçãoEstadual))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14Dam_ContatoResponsavel)
                            .addComponent(jTxtDam_ContatoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jChbDam_Ativo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7Dam_Cep)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel8Dam_Endereço))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDam_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4Dam_CNPJ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtDam_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5Dam_Email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6Dam_Telefone)
                            .addComponent(jTxtDam_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtDam_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTxtDam_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10Dam_Bairro)
                                .addGap(159, 159, 159)
                                .addComponent(jLabel11Dam_Estado)))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12Dam_Cidade)
                            .addComponent(jTxtDam_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jBtnDam_Incluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDam_Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDam_Excluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDam_Confirmar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDam_Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnDam_Pesquisar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jTxtDam_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtDam_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9Dam_Numero)
                                .addComponent(jTxtDam_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2Dam_NomeFantasia)
                                    .addGap(198, 198, 198)
                                    .addComponent(jLabel1Dam_Codigo))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jTxtDam_NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTxtDam_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3Dam_RazãoSocial)
                                .addComponent(jTxtDam_RazãoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2Dam_NomeFantasia)
                            .addComponent(jLabel1Dam_Codigo)
                            .addComponent(jLabel3Dam_RazãoSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtDam_NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtDam_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtDam_RazãoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4Dam_CNPJ))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6Dam_Telefone)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel5Dam_Email, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDam_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7Dam_Cep)
                    .addComponent(jLabel8Dam_Endereço)
                    .addComponent(jLabel9Dam_Numero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDam_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_Endereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10Dam_Bairro)
                    .addComponent(jLabel11Dam_Estado)
                    .addComponent(jLabel12Dam_Cidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDam_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13Dam_InscriçãoEstadual)
                    .addComponent(jLabel14Dam_ContatoResponsavel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDam_InscriçãoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtDam_ContatoResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbDam_Ativo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDam_Incluir)
                    .addComponent(jBtnDam_Alterar)
                    .addComponent(jBtnDam_Excluir)
                    .addComponent(jBtnDam_Confirmar)
                    .addComponent(jBtnDam_Cancelar)
                    .addComponent(jBtnDam_Pesquisar))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDam_ContatoResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDam_ContatoResponsavelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDam_ContatoResponsavelActionPerformed

    private void jBtnDam_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_IncluirActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnDam_IncluirActionPerformed

    private void jBtnDam_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_AlterarActionPerformed
        // TODO add your handling code here:
        habilitar();
    }//GEN-LAST:event_jBtnDam_AlterarActionPerformed

    private void jBtnDam_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_ExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirma Exclusão?");
    }//GEN-LAST:event_jBtnDam_ExcluirActionPerformed

    private void jBtnDam_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnDam_ConfirmarActionPerformed

    private void jBtnDam_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_CancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
    }//GEN-LAST:event_jBtnDam_CancelarActionPerformed

    private void jBtnDam_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDam_PesquisarActionPerformed
        // TODO add your handling code here:
         JOptionPane.showInputDialog(null, "Entre com a chave primária:");
    }//GEN-LAST:event_jBtnDam_PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgDam_Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgDam_Fornecedor dialog = new JDlgDam_Fornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDam_Alterar;
    private javax.swing.JButton jBtnDam_Cancelar;
    private javax.swing.JButton jBtnDam_Confirmar;
    private javax.swing.JButton jBtnDam_Excluir;
    private javax.swing.JButton jBtnDam_Incluir;
    private javax.swing.JButton jBtnDam_Pesquisar;
    private javax.swing.JCheckBox jChbDam_Ativo;
    private javax.swing.JLabel jLabel10Dam_Bairro;
    private javax.swing.JLabel jLabel11Dam_Estado;
    private javax.swing.JLabel jLabel12Dam_Cidade;
    private javax.swing.JLabel jLabel13Dam_InscriçãoEstadual;
    private javax.swing.JLabel jLabel14Dam_ContatoResponsavel;
    private javax.swing.JLabel jLabel1Dam_Codigo;
    private javax.swing.JLabel jLabel2Dam_NomeFantasia;
    private javax.swing.JLabel jLabel3Dam_RazãoSocial;
    private javax.swing.JLabel jLabel4Dam_CNPJ;
    private javax.swing.JLabel jLabel5Dam_Email;
    private javax.swing.JLabel jLabel6Dam_Telefone;
    private javax.swing.JLabel jLabel7Dam_Cep;
    private javax.swing.JLabel jLabel8Dam_Endereço;
    private javax.swing.JLabel jLabel9Dam_Numero;
    private javax.swing.JTextField jTxtDam_Bairro;
    private javax.swing.JTextField jTxtDam_CNPJ;
    private javax.swing.JTextField jTxtDam_Cep;
    private javax.swing.JTextField jTxtDam_Cidade;
    private javax.swing.JTextField jTxtDam_Codigo;
    private javax.swing.JTextField jTxtDam_ContatoResponsavel;
    private javax.swing.JTextField jTxtDam_Email;
    private javax.swing.JTextField jTxtDam_Endereço;
    private javax.swing.JTextField jTxtDam_Estado;
    private javax.swing.JTextField jTxtDam_InscriçãoEstadual;
    private javax.swing.JTextField jTxtDam_NomeFantasia;
    private javax.swing.JTextField jTxtDam_Numero;
    private javax.swing.JTextField jTxtDam_RazãoSocial;
    private javax.swing.JTextField jTxtDam_Telefone;
    // End of variables declaration//GEN-END:variables
}
