/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u11051489121
 */
public class JFramePrincipa extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipa
     */
    public JFramePrincipa() {
        initComponents();
        setTitle("Sistema do IFMS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuDam_Cadastros = new javax.swing.JMenu();
        jMnuDam_Usuarios = new javax.swing.JMenuItem();
        jMnuDam_Clientes = new javax.swing.JMenuItem();
        jMnuDam_Fornecedor = new javax.swing.JMenuItem();
        jMnuDam_Produtos = new javax.swing.JMenuItem();
        jMnuDam_Vendedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuDam_Sair = new javax.swing.JMenuItem();
        jMnuDam_Movimentos = new javax.swing.JMenu();
        jMnuDam_Vendas = new javax.swing.JMenuItem();
        jMnuDam_Venda_Produtos = new javax.swing.JMenuItem();
        jMnuDam_Compras = new javax.swing.JMenuItem();
        jMnuDam_Compras_Produtos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuDam_Cadastros.setText("Cadastros");

        jMnuDam_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuDam_Usuarios.setText("Usuarios");
        jMnuDam_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuDam_UsuariosActionPerformed(evt);
            }
        });
        jMnuDam_Cadastros.add(jMnuDam_Usuarios);

        jMnuDam_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuDam_Clientes.setText("Clientes");
        jMnuDam_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuDam_ClientesActionPerformed(evt);
            }
        });
        jMnuDam_Cadastros.add(jMnuDam_Clientes);

        jMnuDam_Fornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Fornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.png"))); // NOI18N
        jMnuDam_Fornecedor.setText("Fonercedor");
        jMnuDam_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuDam_FornecedorActionPerformed(evt);
            }
        });
        jMnuDam_Cadastros.add(jMnuDam_Fornecedor);

        jMnuDam_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuDam_Produtos.setText("Produtos");
        jMnuDam_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuDam_ProdutosActionPerformed(evt);
            }
        });
        jMnuDam_Cadastros.add(jMnuDam_Produtos);

        jMnuDam_Vendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png"))); // NOI18N
        jMnuDam_Vendedor.setText("Vendedor");
        jMnuDam_Cadastros.add(jMnuDam_Vendedor);
        jMnuDam_Cadastros.add(jSeparator1);

        jMnuDam_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuDam_Sair.setText("Sair");
        jMnuDam_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuDam_SairActionPerformed(evt);
            }
        });
        jMnuDam_Cadastros.add(jMnuDam_Sair);

        jMenuBar1.add(jMnuDam_Cadastros);

        jMnuDam_Movimentos.setText("Movimentos");

        jMnuDam_Vendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMnuDam_Vendas.setText("Vendas");
        jMnuDam_Movimentos.add(jMnuDam_Vendas);

        jMnuDam_Venda_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Venda_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas_produtos.png"))); // NOI18N
        jMnuDam_Venda_Produtos.setText("Vendas_Produtos");
        jMnuDam_Venda_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuDam_Venda_ProdutosActionPerformed(evt);
            }
        });
        jMnuDam_Movimentos.add(jMnuDam_Venda_Produtos);

        jMnuDam_Compras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compras.png"))); // NOI18N
        jMnuDam_Compras.setText("Compras");
        jMnuDam_Movimentos.add(jMnuDam_Compras);

        jMnuDam_Compras_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuDam_Compras_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compra_produtos.png"))); // NOI18N
        jMnuDam_Compras_Produtos.setText("Compras_Produtos");
        jMnuDam_Movimentos.add(jMnuDam_Compras_Produtos);

        jMenuBar1.add(jMnuDam_Movimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuDam_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuDam_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuDam_ProdutosActionPerformed

    private void jMnuDam_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuDam_ClientesActionPerformed
        // TODO add your handling code here:
        JDlgDam_Clientes jDlgDam_Clientes = new JDlgDam_Clientes(null, true);
        jDlgDam_Clientes.setVisible(true);
    }//GEN-LAST:event_jMnuDam_ClientesActionPerformed

    private void jMnuDam_Venda_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuDam_Venda_ProdutosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuDam_Venda_ProdutosActionPerformed

    private void jMnuDam_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuDam_UsuariosActionPerformed
        // TODO add your handling code here:
        JDlgDam_Usuarios jDlgDam_Usuarios = new JDlgDam_Usuarios(null, true);
        jDlgDam_Usuarios.setVisible(true);
    }//GEN-LAST:event_jMnuDam_UsuariosActionPerformed

    private void jMnuDam_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuDam_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuDam_SairActionPerformed

    private void jMnuDam_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuDam_FornecedorActionPerformed
        // TODO add your handling code here:
        JDlgDam_Fornecedor jDlgDam_Fornecedor = new JDlgDam_Fornecedor(null, true);
        jDlgDam_Fornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuDam_FornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuDam_Cadastros;
    private javax.swing.JMenuItem jMnuDam_Clientes;
    private javax.swing.JMenuItem jMnuDam_Compras;
    private javax.swing.JMenuItem jMnuDam_Compras_Produtos;
    private javax.swing.JMenuItem jMnuDam_Fornecedor;
    private javax.swing.JMenu jMnuDam_Movimentos;
    private javax.swing.JMenuItem jMnuDam_Produtos;
    private javax.swing.JMenuItem jMnuDam_Sair;
    private javax.swing.JMenuItem jMnuDam_Usuarios;
    private javax.swing.JMenuItem jMnuDam_Venda_Produtos;
    private javax.swing.JMenuItem jMnuDam_Vendas;
    private javax.swing.JMenuItem jMnuDam_Vendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
